name: protrack_teacher
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  supabase_flutter: ^2.0.0
  image_picker: ^1.1.2
  firebase_auth: ^5.4.1
  cherry_toast: ^1.11.0
  flutter_launcher_icons: ^0.14.3
  syncfusion_flutter_datagrid: ^28.2.3
  flutter_secure_storage: ^9.2.4
  open_file: ^3.5.10
  http: ^0.13.6 
  path_provider: ^2.1.2  
  url_launcher: ^6.2.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
   - assets/
