name: protrack_student
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cherry_toast: ^1.11.0
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  percent_indicator: ^4.2.4
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
